In [ ]:
#Numpy tutorial

In [2]:
#cretion of numpy
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr, type(arr))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [4]:
import time 
size = 10_000_000 # large data set of 10 million numbers 
# Python Lists 
python_list = list(range(size)) 
start = time.time()
list_squared=[x**2 for x in python_list]#squareofallnums
end= time.time() 
print("Python list time:", end -start, "seconds") # NumPy Arrays 
np_array = np.array(python_list) 
start = time.time() 
array_squared = np_array** 2 # vectorized operation 
end = time.time() 
print("NumPy array time:", end -start, "seconds")

Python list time: 1.918689489364624 seconds
NumPy array time: 0.056914567947387695 seconds


In [5]:
arr2 = np.array([1, 2, 3, 4, "prime", 3.14]) 
print(arr2, type(arr2))

['1' '2' '3' '4' 'prime' '3.14'] <class 'numpy.ndarray'>


In [7]:
# Creating NumPy Arrays -from scratch 
arr1 = np.zeros((3, 4)) # 3x4 array of 0s 
print(arr1, arr1.shape) 
arr2 = np.ones((3, 3)) # 3x3 array of 1s 
print(arr2, arr2.shape) 
arr3 = np.full((2, 3), 5) # 2x3 array of 5s 
print(arr3, arr3.shape) 
arr4 = np.eye(3) # Identity matrix of 3x3 
print(arr4, arr4.shape) 
arr5 = np.arange(1, 20, 2) # Elements in range(1, 20) 
print(arr5, arr5.shape) 
arr6 = np.linspace(0, 10, 5) # Evenly spaced array 
print(arr6, arr6.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)


In [8]:
#Useful Attributes 
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11, 12]])
print(arr.shape)# Dimensions -(4 x 3) 
print(arr.size) # Total elements -(12) 
print(arr.ndim) # Number of dimensions -2 
print(arr.dtype)# Data type object -int64 
print(arr.itemsize) # Size of each element in bytes -8 for int64rajshani7754@gmail.com


(4, 3)
12
2
int64
8


In [ ]:
# from AIML book revision

In [1]:
# 1. Data handling and preprocessing
import numpy as np

In [3]:
data = np.array([[50, 30], [80, 60], [90, 70]])
# Normalize the data between 0 and 1
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
normalized

array([[0.33333333, 0.        ],
       [0.83333333, 0.5       ],
       [1.        , 0.66666667]])

In [6]:
data

array([[50, 30],
       [80, 60],
       [90, 70]])

In [8]:
# Creating Numpy array
arr1 = np.array([1,2,3]) #1D array
arr1

array([1, 2, 3])

In [9]:
arr2 = np.array([[1,2,3], [4,5,6]]) #2d array
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 2*3 array of zero
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 3*3 array of ones
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
full = np.full((3,3), 2)
full

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])